# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.srcs/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/gps_design_PmodGPS_0_0.xci
# IP: The module: 'gps_design_PmodGPS_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/src/PmodGPS_axi_uart16550_0_0/PmodGPS_axi_uart16550_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodGPS_axi_uart16550_0_0 || ORIG_REF_NAME==PmodGPS_axi_uart16550_0_0} -quiet] -quiet

# IP: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/src/PmodGPS_axi_gpio_0_0/PmodGPS_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodGPS_axi_gpio_0_0 || ORIG_REF_NAME==PmodGPS_axi_gpio_0_0} -quiet] -quiet

# IP: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/src/PmodGPS_pmod_bridge_0_0/PmodGPS_pmod_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodGPS_pmod_bridge_0_0 || ORIG_REF_NAME==PmodGPS_pmod_bridge_0_0} -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/src/PmodGPS_axi_uart16550_0_0/PmodGPS_axi_uart16550_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodGPS_axi_uart16550_0_0 || ORIG_REF_NAME==PmodGPS_axi_uart16550_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/src/PmodGPS_axi_uart16550_0_0/PmodGPS_axi_uart16550_0_0_ooc.xdc

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/src/PmodGPS_axi_uart16550_0_0/PmodGPS_axi_uart16550_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodGPS_axi_uart16550_0_0 || ORIG_REF_NAME==PmodGPS_axi_uart16550_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/gps_design_PmodGPS_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gps_design_PmodGPS_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/src/PmodGPS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gps_design_PmodGPS_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/src/PmodGPS_axi_gpio_0_0/PmodGPS_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodGPS_axi_gpio_0_0 || ORIG_REF_NAME==PmodGPS_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/src/PmodGPS_axi_gpio_0_0/PmodGPS_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/src/PmodGPS_axi_gpio_0_0/PmodGPS_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodGPS_axi_gpio_0_0 || ORIG_REF_NAME==PmodGPS_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/src/PmodGPS_pmod_bridge_0_0/PmodGPS_pmod_bridge_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodGPS_pmod_bridge_0_0 || ORIG_REF_NAME==PmodGPS_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/src/PmodGPS_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# IP: C:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.srcs/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/gps_design_PmodGPS_0_0.xci
# IP: The module: 'gps_design_PmodGPS_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/src/PmodGPS_axi_uart16550_0_0/PmodGPS_axi_uart16550_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodGPS_axi_uart16550_0_0 || ORIG_REF_NAME==PmodGPS_axi_uart16550_0_0} -quiet] -quiet

# IP: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/src/PmodGPS_axi_gpio_0_0/PmodGPS_axi_gpio_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodGPS_axi_gpio_0_0 || ORIG_REF_NAME==PmodGPS_axi_gpio_0_0} -quiet] -quiet

# IP: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/src/PmodGPS_pmod_bridge_0_0/PmodGPS_pmod_bridge_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodGPS_pmod_bridge_0_0 || ORIG_REF_NAME==PmodGPS_pmod_bridge_0_0} -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/src/PmodGPS_axi_uart16550_0_0/PmodGPS_axi_uart16550_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodGPS_axi_uart16550_0_0 || ORIG_REF_NAME==PmodGPS_axi_uart16550_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/src/PmodGPS_axi_uart16550_0_0/PmodGPS_axi_uart16550_0_0_ooc.xdc

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/src/PmodGPS_axi_uart16550_0_0/PmodGPS_axi_uart16550_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodGPS_axi_uart16550_0_0 || ORIG_REF_NAME==PmodGPS_axi_uart16550_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/gps_design_PmodGPS_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gps_design_PmodGPS_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/src/PmodGPS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gps_design_PmodGPS_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/src/PmodGPS_axi_gpio_0_0/PmodGPS_axi_gpio_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodGPS_axi_gpio_0_0 || ORIG_REF_NAME==PmodGPS_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/src/PmodGPS_axi_gpio_0_0/PmodGPS_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/src/PmodGPS_axi_gpio_0_0/PmodGPS_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodGPS_axi_gpio_0_0 || ORIG_REF_NAME==PmodGPS_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/src/PmodGPS_pmod_bridge_0_0/PmodGPS_pmod_bridge_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodGPS_pmod_bridge_0_0 || ORIG_REF_NAME==PmodGPS_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_PmodGPS_0_0/src/PmodGPS_pmod_bridge_0_0/src/pmod_concat_ooc.xdc
