# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.srcs/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/finalproject_design_PmodBT2_0_0.xci
# IP: The module: 'finalproject_design_PmodBT2_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/src/PmodBT2_axi_uart16550_0_0/PmodBT2_axi_uart16550_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodBT2_axi_uart16550_0_0 || ORIG_REF_NAME==PmodBT2_axi_uart16550_0_0} -quiet] -quiet

# IP: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/src/PmodBT2_axi_gpio_0_0/PmodBT2_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodBT2_axi_gpio_0_0 || ORIG_REF_NAME==PmodBT2_axi_gpio_0_0} -quiet] -quiet

# IP: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/src/PmodBT2_pmod_bridge_0_0/PmodBT2_pmod_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodBT2_pmod_bridge_0_0 || ORIG_REF_NAME==PmodBT2_pmod_bridge_0_0} -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/src/PmodBT2_axi_uart16550_0_0/PmodBT2_axi_uart16550_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodBT2_axi_uart16550_0_0 || ORIG_REF_NAME==PmodBT2_axi_uart16550_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/src/PmodBT2_axi_uart16550_0_0/PmodBT2_axi_uart16550_0_0_ooc.xdc

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/src/PmodBT2_axi_uart16550_0_0/PmodBT2_axi_uart16550_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodBT2_axi_uart16550_0_0 || ORIG_REF_NAME==PmodBT2_axi_uart16550_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/finalproject_design_PmodBT2_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'finalproject_design_PmodBT2_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/src/PmodBT2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'finalproject_design_PmodBT2_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/src/PmodBT2_axi_gpio_0_0/PmodBT2_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodBT2_axi_gpio_0_0 || ORIG_REF_NAME==PmodBT2_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/src/PmodBT2_axi_gpio_0_0/PmodBT2_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/src/PmodBT2_axi_gpio_0_0/PmodBT2_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodBT2_axi_gpio_0_0 || ORIG_REF_NAME==PmodBT2_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/src/PmodBT2_pmod_bridge_0_0/PmodBT2_pmod_bridge_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodBT2_pmod_bridge_0_0 || ORIG_REF_NAME==PmodBT2_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/src/PmodBT2_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# IP: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.srcs/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/finalproject_design_PmodBT2_0_0.xci
# IP: The module: 'finalproject_design_PmodBT2_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/src/PmodBT2_axi_uart16550_0_0/PmodBT2_axi_uart16550_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodBT2_axi_uart16550_0_0 || ORIG_REF_NAME==PmodBT2_axi_uart16550_0_0} -quiet] -quiet

# IP: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/src/PmodBT2_axi_gpio_0_0/PmodBT2_axi_gpio_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodBT2_axi_gpio_0_0 || ORIG_REF_NAME==PmodBT2_axi_gpio_0_0} -quiet] -quiet

# IP: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/src/PmodBT2_pmod_bridge_0_0/PmodBT2_pmod_bridge_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodBT2_pmod_bridge_0_0 || ORIG_REF_NAME==PmodBT2_pmod_bridge_0_0} -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/src/PmodBT2_axi_uart16550_0_0/PmodBT2_axi_uart16550_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodBT2_axi_uart16550_0_0 || ORIG_REF_NAME==PmodBT2_axi_uart16550_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/src/PmodBT2_axi_uart16550_0_0/PmodBT2_axi_uart16550_0_0_ooc.xdc

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/src/PmodBT2_axi_uart16550_0_0/PmodBT2_axi_uart16550_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodBT2_axi_uart16550_0_0 || ORIG_REF_NAME==PmodBT2_axi_uart16550_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/finalproject_design_PmodBT2_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'finalproject_design_PmodBT2_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/src/PmodBT2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'finalproject_design_PmodBT2_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/src/PmodBT2_axi_gpio_0_0/PmodBT2_axi_gpio_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodBT2_axi_gpio_0_0 || ORIG_REF_NAME==PmodBT2_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/src/PmodBT2_axi_gpio_0_0/PmodBT2_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/src/PmodBT2_axi_gpio_0_0/PmodBT2_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodBT2_axi_gpio_0_0 || ORIG_REF_NAME==PmodBT2_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/src/PmodBT2_pmod_bridge_0_0/PmodBT2_pmod_bridge_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodBT2_pmod_bridge_0_0 || ORIG_REF_NAME==PmodBT2_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_PmodBT2_0_0/src/PmodBT2_pmod_bridge_0_0/src/pmod_concat_ooc.xdc
