# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/EmbeddedSystems2/Z7_7010_7020.xdc

# Block Designs: bd/gps_design/gps_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gps_design || ORIG_REF_NAME==gps_design} -quiet] -quiet

# IP: bd/gps_design/ip/gps_design_processing_system7_0_0/gps_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gps_design_processing_system7_0_0 || ORIG_REF_NAME==gps_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/gps_design/ip/gps_design_PmodGPS_0_0/gps_design_PmodGPS_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gps_design_PmodGPS_0_0 || ORIG_REF_NAME==gps_design_PmodGPS_0_0} -quiet] -quiet

# IP: bd/gps_design/ip/gps_design_xbar_0/gps_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gps_design_xbar_0 || ORIG_REF_NAME==gps_design_xbar_0} -quiet] -quiet

# IP: bd/gps_design/ip/gps_design_ps7_0_axi_periph_0/gps_design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gps_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==gps_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/gps_design/ip/gps_design_rst_ps7_0_50M_0/gps_design_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gps_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==gps_design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/gps_design/ip/gps_design_xlconcat_0_0/gps_design_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gps_design_xlconcat_0_0 || ORIG_REF_NAME==gps_design_xlconcat_0_0} -quiet] -quiet

# IP: bd/gps_design/ip/gps_design_auto_pc_0/gps_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gps_design_auto_pc_0 || ORIG_REF_NAME==gps_design_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/gps_design_ooc.xdc
