# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.srcs/sources_1/bd/gps_design/ip/gps_design_rst_ps7_0_50M_0/gps_design_rst_ps7_0_50M_0.xci
# IP: The module: 'gps_design_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_rst_ps7_0_50M_0/gps_design_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gps_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_rst_ps7_0_50M_0/gps_design_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gps_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_rst_ps7_0_50M_0/gps_design_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gps_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.srcs/sources_1/bd/gps_design/ip/gps_design_rst_ps7_0_50M_0/gps_design_rst_ps7_0_50M_0.xci
# IP: The module: 'gps_design_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_rst_ps7_0_50M_0/gps_design_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gps_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_rst_ps7_0_50M_0/gps_design_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gps_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/singlePmods/gps/gps.gen/sources_1/bd/gps_design/ip/gps_design_rst_ps7_0_50M_0/gps_design_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gps_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
