# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.srcs/sources_1/bd/finalproject_design/ip/finalproject_design_xbar_0/finalproject_design_xbar_0.xci
# IP: The module: 'finalproject_design_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_xbar_0/finalproject_design_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'finalproject_design_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.srcs/sources_1/bd/finalproject_design/ip/finalproject_design_xbar_0/finalproject_design_xbar_0.xci
# IP: The module: 'finalproject_design_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johnr/Projects/EmbeddedSystems2_FinalProject/finalproject/finalproject.gen/sources_1/bd/finalproject_design/ip/finalproject_design_xbar_0/finalproject_design_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'finalproject_design_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
